vagrant/rhel7-build: no longer need 'develop' version of salt
in fact, it does damage; salt 2015.2.0-935-g41d0c1a fails to
render top.sls correctly with:

[CRITICAL] Pillar render error: Rendering Primary Top file failed,
render error:
'NoneType' object has no attribute 'endswith'

Signed-off-by: Dan Mick <dan.mick@redhat.com>